server:
 port: 8080

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/blooddonationsystem?useSSL=false&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password:
 mail:
  host: smtp.gmail.com
  port: 587
  username: hantnse180242@fpt.edu.vn
  password: chvbgrrguahjuogu
 swagger-ui:
  path: /swagger-ui.html
  info:
   title: Tên API của bạn
   version: v1
   description: Mô tả API của bạn

  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true

jpa:
 show-sql: true
hibernate:
 ddl-auto: none
properties:
 hibernate:
 dialect: org.hibernate.dialect.MySQL8Dialect
 format_sql: true

servlet:
 multipart:
 max-file-size: 10MB
 max-request-size: 10MB

api:
 prefix: api/v1

springdoc:
 api-docs:
  path: /api-docs

jwt:
 expiration: 2592000
 secretKey: Xp/b5+tEAufHBk9CiQzd9XK1Vs8iLG8Nk+ohg2Jq2qM=

