server:
 port: 8080

spring:
 servlet:
  multipart:
   max-file-size: 10MB
   max-request-size: 10MB
 datasource:
  url: jdbc:mysql://localhost:3306/blooddonationsystem?useSSL=false&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password:
 mail:
  host: smtp.gmail.com
  port: 587
  username: hantnse180242@fpt.edu.vn
  password: chvbgrrguahjuogu
 swagger-ui:
  path: /swagger-ui.html
  info:
   title: Tên API của bạn
   version: v1
   description: Mô tả API của bạn
 security:
  oauth2:
   client:
    registration:
     google:
      client-id: 331644149748-lq5svlpe8d0je01ulmpblecb2r24l780.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: "{baseUrl}/login/oauth2/code/google"
      scope: openid, profile, email
      client-name: Google
      authorization-grant-type: authorization_code
      provider: google
     facebook:
      client-id: 1007654770988152
      client-secret: 5adb1d315754ac7e7e26b09d4c8b8b17
      redirect-uri: "{baseUrl}/auth/facebook/callback"
      scope: email, public_profile
      client-name: Facebook
      authorization-grant-type: authorization_code
      provider: facebook
    provider:
     google:
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      user-name-attribute: sub
     facebook:
      authorization-uri: https://www.facebook.com/v21.0/dialog/oauth
      token-uri: https://graph.facebook.com/oauth/access_token
      user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
      user-name-attribute: id

  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true

jpa:
 show-sql: true
hibernate:
 ddl-auto: none
properties:
 hibernate:
 dialect: org.hibernate.dialect.MySQL8Dialect
 format_sql: true

servlet:
 multipart:
 max-file-size: 10MB
 max-request-size: 10MB

api:
 prefix: api/v1

springdoc:
 api-docs:
  path: /api-docs

jwt:
 expiration: 2555000
 secretKey: Xp_b5-tEAufHBk9CiQzd9XK1Vs8iLG8Nk-ohg2Jq2qM

frontend:
 redirect-url: http://localhost:4200/login/success
